repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --line-length=120]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
